# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stacked', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question_obj',
            field=models.ForeignKey(default=27, on_delete=django.db.models.deletion.CASCADE, to='stacked.Question'),
            preserve_default=False,
        ),
    ]
